# -*- coding: utf-8 -*-
"""dat_viz_nbs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/NovaVolunteer/vscode/blob/main/dat_viz_nbs.ipynb

<a target="_blank" href="https://colab.research.google.com/github/NovaVolunteer/vscode/blob/main/dat_viz_nbs.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

## Set up environment
"""

import pandas as pd #data manipulation
import numpy as np #arrays & math
import matplotlib.pyplot as plt #data visualization
import seaborn as sns #statistical visualization
from scipy.stats import gaussian_kde #scientific computing
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# read in the data
url = "https://github.com/UVADS/DS-3021/raw/refs/heads/main/data/NBA_Perf_22.csv"

df = pd.read_csv(url, encoding='latin-1')

## check the data

df.head(10)

df.info()

df.describe() # Use this to get a quick summary of the data. It will give you the count, mean,
# standard deviation, min, max, and quartiles for each numeric column in the DataFrame.

# generate a scatter plot to visualize the relationship between two numeric variables, for example, 'Points' and 'Minutes Played'
sns.scatterplot(data=df, x='MP', y='PTS')
plt.title('Scatter Plot of Points vs. Minutes Played')
plt.xlabel('Minutes Played')
plt.ylabel('Points')
plt.show()

# Let's create a bar chart to show the average points scored by players in different positions.
# We will group the data by 'Pos' and calculate the mean of 'PTS' for each position.

avg_points_by_position = df.groupby('Pos')['PTS'].mean().reset_index() # This groups the data by 'Pos', calculates the mean of 'PTS' for each group,
#and resets the index to get a DataFrame. Indexing by 'Pos' allows us to easily plot the average points for each position.

sns.barplot(data=avg_points_by_position, x='Pos', y='PTS') # This creates a bar plot with 'Pos' on the x-axis and the average 'PTS' on the y-axis.

plt.title('Average Points by Position') # All labels and titles
plt.xlabel('Position')
plt.ylabel('Average Points')
plt.show()

# Create a density plot to visualize the distribution of points scored by players.
sns.kdeplot(data=df, x='PTS', fill=True) # This creates a kernel density estimate plot for the 'PTS' column,
# which shows the distribution of points scored by players.
plt.title('Density Plot of Points Scored') # All labels and titles
plt.xlabel('Points Scored')
plt.ylabel('Density')
plt.show()

# We can use modeling to better understand the patterns of player performance and make predictions about future performance.
# For example, we could use K-means clustering to group players based on their performance metrics, or we could use linear regression to predict a player's points based on their minutes played and other factors.
# Let's build a k-means clustering model to group players based on their points and minutes played.

#Build a model
scaler = StandardScaler()
kmeans = KMeans(n_clusters=3)
kmeans.fit(scaler.fit_transform(df[['MP', 'PTS']]))
df['Cluster'] = kmeans.labels_

#Visualize the clusters
sns.scatterplot(data=df, x='MP', y='PTS', hue='Cluster', palette='Set1')
plt.title('K-means Clustering of Players Based on Points and Minutes Played')
plt.xlabel('Minutes Played')
plt.ylabel('Points')
plt.legend(title='Cluster')
plt.show()